# Generated by Django 3.1.3 on 2021-01-18 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0002_auto_20210113_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='district',
        ),
        migrations.RemoveField(
            model_name='rice',
            name='district',
        ),
    ]
