# Generated by Django 3.1.3 on 2021-01-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0003_auto_20210118_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='rice',
            name='rainfall',
            field=models.IntegerField(default=0),
        ),
    ]
